version: "3"

services:
    jekyll:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/site
        ports:
            - "4000:4000"
        command: bundle exec jekyll serve --host 0.0.0.0 --livereload
